steer_joint_names: &steer_joint_names
  - steer_left_joint
  - steer_right_joint

wheel_joint_names: &wheel_joint_names
  - front_left_joint
  - front_right_joint
  - rear_right_joint
  - rear_left_joint


# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100


ackermann_controller:
  type: "ackermann_steering_controller/AckermannSteeringController"
  rear_wheel: 'rear_left_joint'
  front_steer: 'front_left_joint'
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]


diff_controller:
  type: "diff_drive_controller/DiffDriveController"
  rear_wheel: 'rear_left_joint'
  front_steer: 'front_left_joint'
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]